stages:          # List of stages for jobs, and their order of execution
  - test

po-test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - ls
